### ISSUE TITLE
Cargo build fails

### ISSUE THREAD

**Issue by israellevin** [the-drunk-coder/megra.rs#6]
The cargo build fails with a jack related error message. I am using pipewire and do not have jack installed.

```sh
$ rustup default nightly
...
$ RUST_BACKTRACE=true CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true cargo install megra_rs --features ringbuffer
...
   Compiling url v2.5.2
error: failed to run custom build command for `jack-sys v0.5.1`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installweTFvg/release/build/jack-sys-f530175b21ce43dc/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=JACK_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=JACK_STATIC
  cargo:rerun-if-env-changed=JACK_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at /home/i/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jack-sys-0.5.1/build.rs:13:23:
  called `Result::unwrap()` on an `Err` value: "\npkg-config exited with status code 1\n> PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags jack\n\nThe system library `jack` required by crate `jack-sys` was not found.\nThe file `jack.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.\nThe PKG_CONFIG_PATH environment variable is not set.\n\nHINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `jack.pc`.\n"
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/5069856495870486134dd2ca0b0e2516308c5c2a/library/std/src/panicking.rs:665:5
     1: core::panicking::panic_fmt
               at /rustc/5069856495870486134dd2ca0b0e2516308c5c2a/library/core/src/panicking.rs:74:14
     2: core::result::unwrap_failed
               at /rustc/5069856495870486134dd2ca0b0e2516308c5c2a/library/core/src/result.rs:1679:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/5069856495870486134dd2ca0b0e2516308c5c2a/library/core/src/result.rs:1102:23
     4: build_script_build::main
               at ./build.rs:13:9
     5: core::ops::function::FnOnce::call_once
               at /rustc/5069856495870486134dd2ca0b0e2516308c5c2a/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `megra_rs v0.0.12`, intermediate artifacts can be found at `/tmp/cargo-installweTFvg`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by the-drunk-coder** [comment]
Hmm I think you'll have to install `libjack` (i.e. the `jack2` package on arch, on Debian-based systems it's typically something like `libjack-dev`). Let me know if that works.

EDIT: oops, sorry I didn't read the first sentence closely enough, with pipewire you still need `pw-jack` (the `libjack` drop-in replacements for pipewire), as Mégra uses the Jack interface, even to connect to pipewire ...

I should put a note in the documentation, thanks for the hint :)

**Comment by israellevin** [comment]
After `apt install pipewire-jack` I get a new error, now specifying alsa as the problem

```sh
$ RUST_BACKTRACE=full CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true cargo install megra_rs --features ringbuffer
...
   Compiling http v0.2.12
error: failed to run custom build command for `alsa-sys v0.3.1`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installBEHKQz/release/build/alsa-sys-0e73a0f248fc2c50/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=ALSA_NO_PKG_CONFIG
...  
```

So I tried `apt install libasound2-dev`, which got me back to jack message!
```sh
   Compiling atspi v0.19.0
error: failed to run custom build command for `jack-sys v0.5.1`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installcDFddg/release/build/jack-sys-f530175b21ce43dc/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=JACK_NO_PKG_CONFIG
```

Eventually I tried `apt get install libjack-dev` and that took care of it. Now I can run Mégra! Thanks!

**Comment by the-drunk-coder** [comment]
I added a note to the "Installation" chapter in the docs, thanks for the feedback :)
